name: friendo_meinprojekt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  cloud_firestore
  
  flutter:
    sdk: flutter
  #flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

#flutter_native_splash: 
  #color: "#FFF5F1"
  #background_image: "assets/images/Logo.png"
  #fullscreen: true